In [1]:
# 필요한 모듈 불러오기
import pandas as pd
import numpy as np

In [2]:
# 데이터 파일 불러오기
df = pd.read_csv("./KGU_3rd_ORIGIN_KGUAREADOITEM_20200101000000.csv")

In [3]:
df

         2020-01-01  00  수요일   경상남도 창원시 마산회원구      치킨
0        2020-01-01   1  수요일    경기도       광명시      찜탕
1        2020-01-01   0  수요일  서울특별시       은평구      치킨
2        2020-01-01   1  수요일    경기도      의정부시      한식
3        2020-01-01   1  수요일    경기도   고양시 덕양구      한식
4        2020-01-01   0  수요일    경기도       부천시   족발/보쌈
...             ...  ..  ...    ...       ...     ...
6011048  2020-06-30  22  화요일    경기도       광명시  배달전문업체
6011049  2020-06-30  20  화요일   충청북도   청주시 청원구  카페/디저트
6011050  2020-06-30  21  화요일   전라북도       군산시      분식
6011051  2020-06-30  21  화요일    경기도      의정부시   족발/보쌈
6011052  2020-06-30  21  화요일  인천광역시       부평구      한식

[6011053 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6011053 entries, 0 to 6011052
Data columns (total 6 columns):
 #   Column      Dtype
---  ------      -----
 0   2020-01-01  object
 1   00          int64
 2   수요일         object
 3   경상남도        object
 4   창원시 마산회원구   object
 5   치킨          object
dtypes: int64(1), object(5)
memory usage: 275.2+ MB

In [5]:
df['2020-01-01'] = pd.to_datetime(df['2020-01-01'])

In [6]:
# 결측치 확인
df.isnull().sum()

2020-01-01    0
00            0
수요일           0
경상남도          0
창원시 마산회원구     0
치킨            0
dtype: int64

In [9]:
# 컬럼명 변경
df.rename(columns={'2020-01-01':'년월일'}, inplace=True)
df.rename(columns={'00':'주문시간'}, inplace=True)
df.rename(columns={'경상남도':'시도'},inplace=True)
df.rename(columns={'수요일':'요일'},inplace=True)
df.rename(columns={'창원시 마산회원구':'시군구'},inplace=True)
df.rename(columns={'치킨':'음식분류'},inplace=True)

In [10]:
df

               년월일  주문시간   요일     시도      시군구    음식분류
0       2020-01-01     1  수요일    경기도      광명시      찜탕
1       2020-01-01     0  수요일  서울특별시      은평구      치킨
2       2020-01-01     1  수요일    경기도     의정부시      한식
3       2020-01-01     1  수요일    경기도  고양시 덕양구      한식
4       2020-01-01     0  수요일    경기도      부천시   족발/보쌈
...            ...   ...  ...    ...      ...     ...
6011048 2020-06-30    22  화요일    경기도      광명시  배달전문업체
6011049 2020-06-30    20  화요일   충청북도  청주시 청원구  카페/디저트
6011050 2020-06-30    21  화요일   전라북도      군산시      분식
6011051 2020-06-30    21  화요일    경기도     의정부시   족발/보쌈
6011052 2020-06-30    21  화요일  인천광역시      부평구      한식

[6011053 rows x 6 columns]

In [11]:
# 시도에서 서울특별시에 해당하는 데이터만 추출
df_seoul = df.loc[df['시도'].isin(['서울특별시'])]

In [12]:
df_seoul

               년월일  주문시간   요일     시도   시군구    음식분류
1       2020-01-01     0  수요일  서울특별시   은평구      치킨
6       2020-01-01     1  수요일  서울특별시   구로구      분식
8       2020-01-01     0  수요일  서울특별시  영등포구      치킨
24      2020-01-01     0  수요일  서울특별시  영등포구      치킨
30      2020-01-01     1  수요일  서울특별시   금천구      치킨
...            ...   ...  ...    ...   ...     ...
6011014 2020-06-30    23  화요일  서울특별시   은평구      치킨
6011020 2020-06-30    22  화요일  서울특별시   구로구      치킨
6011042 2020-06-30    21  화요일  서울특별시   동작구  카페/디저트
6011045 2020-06-30    22  화요일  서울특별시   구로구      분식
6011046 2020-06-30    21  화요일  서울특별시   구로구      분식

[972688 rows x 6 columns]

In [13]:
df_seoul.reset_index()

          index        년월일  주문시간   요일     시도   시군구    음식분류
0             1 2020-01-01     0  수요일  서울특별시   은평구      치킨
1             6 2020-01-01     1  수요일  서울특별시   구로구      분식
2             8 2020-01-01     0  수요일  서울특별시  영등포구      치킨
3            24 2020-01-01     0  수요일  서울특별시  영등포구      치킨
4            30 2020-01-01     1  수요일  서울특별시   금천구      치킨
...         ...        ...   ...  ...    ...   ...     ...
972683  6011014 2020-06-30    23  화요일  서울특별시   은평구      치킨
972684  6011020 2020-06-30    22  화요일  서울특별시   구로구      치킨
972685  6011042 2020-06-30    21  화요일  서울특별시   동작구  카페/디저트
972686  6011045 2020-06-30    22  화요일  서울특별시   구로구      분식
972687  6011046 2020-06-30    21  화요일  서울특별시   구로구      분식

[972688 rows x 7 columns]

In [14]:
df_seoul.reset_index(drop=True, inplace=True)

In [15]:
df_seoul

              년월일  주문시간   요일     시도   시군구    음식분류
0      2020-01-01     0  수요일  서울특별시   은평구      치킨
1      2020-01-01     1  수요일  서울특별시   구로구      분식
2      2020-01-01     0  수요일  서울특별시  영등포구      치킨
3      2020-01-01     0  수요일  서울특별시  영등포구      치킨
4      2020-01-01     1  수요일  서울특별시   금천구      치킨
...           ...   ...  ...    ...   ...     ...
972683 2020-06-30    23  화요일  서울특별시   은평구      치킨
972684 2020-06-30    22  화요일  서울특별시   구로구      치킨
972685 2020-06-30    21  화요일  서울특별시   동작구  카페/디저트
972686 2020-06-30    22  화요일  서울특별시   구로구      분식
972687 2020-06-30    21  화요일  서울특별시   구로구      분식

[972688 rows x 6 columns]

In [16]:
df_seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 972688 entries, 0 to 972687
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   년월일     972688 non-null  datetime64[ns]
 1   주문시간    972688 non-null  int64
 2   요일      972688 non-null  object
 3   시도      972688 non-null  object
 4   시군구     972688 non-null  object
 5   음식분류    972688 non-null  object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 44.5+ MB

In [17]:
df_seoul.to_csv("202001~202006지역별요일별배달품목.csv")