In [2]:
# 필요한 모듈 불러오기
import pandas as pd
import numpy as np

In [3]:
# 데이터 파일 불러오기
df = pd.read_csv("./KGU_3rd_ORIGIN_KGUAREADOITEM_20200101000000.csv")

In [3]:
df

         2019-07-31  00  수요일    경기도  고양시 일산서구      피자
0        2019-07-31   0  수요일    경기도  고양시 일산동구  카페/디저트
1        2019-07-31   0  수요일   전라남도       순천시      치킨
2        2019-07-31   0  수요일    경기도      의정부시   족발/보쌈
3        2019-07-31   0  수요일  서울특별시      영등포구      치킨
4        2019-07-31   0  수요일    경기도      의정부시      한식
...             ...  ..  ...    ...       ...     ...
3890863  2019-12-31  23  화요일    경기도       부천시      치킨
3890864  2019-12-31  23  화요일    경기도      남양주시      중식
3890865  2019-12-31  23  화요일    경기도      의정부시      치킨
3890866  2019-12-31  23  화요일    경기도   안양시 동안구       회
3890867  2019-12-31  23  화요일   경상남도       진주시       회

[3890868 rows x 6 columns]

In [4]:
# 결측치 확인
df.isnull().sum()

2020-01-01    0
00            0
수요일           0
경상남도          0
창원시 마산회원구     0
치킨            0
dtype: int64

In [5]:
# 컬럼명 변경
df.rename(columns={'2020-01-01':'년월일'}, inplace=True)
df.rename(columns={'00':'주문시간'}, inplace=True)
df.rename(columns={'경상남도':'시도'},inplace=True)
df.rename(columns={'수요일':'요일'},inplace=True)
df.rename(columns={'창원시 마산회원구':'시군구'},inplace=True)
df.rename(columns={'치킨':'음식분류'},inplace=True)

In [6]:
df

                년월일  주문시간   요일     시도      시군구    음식분류
0        2020-01-01     1  수요일    경기도      광명시      찜탕
1        2020-01-01     0  수요일  서울특별시      은평구      치킨
2        2020-01-01     1  수요일    경기도     의정부시      한식
3        2020-01-01     1  수요일    경기도  고양시 덕양구      한식
4        2020-01-01     0  수요일    경기도      부천시   족발/보쌈
...             ...   ...  ...    ...      ...     ...
6011048  2020-06-30    22  화요일    경기도      광명시  배달전문업체
6011049  2020-06-30    20  화요일   충청북도  청주시 청원구  카페/디저트
6011050  2020-06-30    21  화요일   전라북도      군산시      분식
6011051  2020-06-30    21  화요일    경기도     의정부시   족발/보쌈
6011052  2020-06-30    21  화요일  인천광역시      부평구      한식

[6011053 rows x 6 columns]

In [7]:
# 시도에서 서울특별시에 해당하는 데이터만 추출
df_seoul = df.loc[df['시도'].isin(['서울특별시'])]

In [8]:
# 인덱스 기준을 년월일로 수정
df_seoul.set_index('년월일', inplace=True)

In [9]:
df_seoul

            주문시간   요일     시도   시군구    음식분류
년월일
2020-01-01     0  수요일  서울특별시   은평구      치킨
2020-01-01     1  수요일  서울특별시   구로구      분식
2020-01-01     0  수요일  서울특별시  영등포구      치킨
2020-01-01     0  수요일  서울특별시  영등포구      치킨
2020-01-01     1  수요일  서울특별시   금천구      치킨
...          ...  ...    ...   ...     ...
2020-06-30    23  화요일  서울특별시   은평구      치킨
2020-06-30    22  화요일  서울특별시   구로구      치킨
2020-06-30    21  화요일  서울특별시   동작구  카페/디저트
2020-06-30    22  화요일  서울특별시   구로구      분식
2020-06-30    21  화요일  서울특별시   구로구      분식

[972688 rows x 5 columns]

In [10]:
df_seoul = df_seoul[df_seoul.음식분류 != '심부름']
df_seoul = df_seoul[df_seoul.음식분류 != '야식']
df_seoul = df_seoul[df_seoul.음식분류 != '배달전문업체']

In [11]:
df_seoul

            주문시간   요일     시도   시군구    음식분류
년월일
2020-01-01     0  수요일  서울특별시   은평구      치킨
2020-01-01     1  수요일  서울특별시   구로구      분식
2020-01-01     0  수요일  서울특별시  영등포구      치킨
2020-01-01     0  수요일  서울특별시  영등포구      치킨
2020-01-01     1  수요일  서울특별시   금천구      치킨
...          ...  ...    ...   ...     ...
2020-06-30    23  화요일  서울특별시   은평구      치킨
2020-06-30    22  화요일  서울특별시   구로구      치킨
2020-06-30    21  화요일  서울특별시   동작구  카페/디저트
2020-06-30    22  화요일  서울특별시   구로구      분식
2020-06-30    21  화요일  서울특별시   구로구      분식

[913880 rows x 5 columns]

In [12]:
df_seoul.to_csv("202001~202006지역별요일별배달품목.csv")