In [18]:
# 필요한 모듈 불러오기
import pandas as pd
import numpy as np

In [19]:
# 데이터 파일 불러오기
df = pd.read_csv("./KGU_3rd_ORIGIN_KGUAREADOITEM_20200701000000.csv")

In [20]:
df

        ﻿2020-07-01  01  수요일    경기도      광명시      피자
0        2020-07-01   6  수요일    경기도     의정부시  배달전문업체
1        2020-07-01   7  수요일    경기도     의정부시      찜탕
2        2020-07-01   0  수요일    경기도  고양시 덕양구      야식
3        2020-07-01   1  수요일  인천광역시      부평구      중식
4        2020-07-01   0  수요일  서울특별시     영등포구      치킨
...             ...  ..  ...    ...      ...     ...
6224966  2020-12-31  23  목요일    경기도      포천시   족발/보쌈
6224967  2020-12-31  23  목요일    경기도     의정부시       회
6224968  2020-12-31  23  목요일    경기도      부천시      치킨
6224969  2020-12-31  23  목요일    경기도  안산시 상록구      피자
6224970  2020-12-31  23  목요일   경상북도      김천시      치킨

[6224971 rows x 6 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6224971 entries, 0 to 6224970
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   ﻿2020-07-01  object
 1   01           int64
 2   수요일          object
 3   경기도          object
 4   광명시          object
 5   피자           object
dtypes: int64(1), object(5)
memory usage: 285.0+ MB

In [22]:
df['﻿2020-07-01'] = pd.to_datetime(df['﻿2020-07-01'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6224971 entries, 0 to 6224970
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   ﻿2020-07-01  datetime64[ns]
 1   01           int64
 2   수요일          object
 3   경기도          object
 4   광명시          object
 5   피자           object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 285.0+ MB

In [25]:
# 결측치 확인
df.isnull().sum()

﻿2020-07-01    0
01             0
수요일            0
경기도            0
광명시            0
피자             0
dtype: int64

In [26]:
# 컬럼명 변경
df.rename(columns={'﻿2020-07-01':'년월일'}, inplace=True)
df.rename(columns={'01':'주문시간'}, inplace=True)
df.rename(columns={'경기도':'시도'},inplace=True)
df.rename(columns={'수요일':'요일'},inplace=True)
df.rename(columns={'의정부시':'시군구'},inplace=True)
df.rename(columns={'피자':'음식분류'},inplace=True)

In [27]:
df

               년월일  주문시간   요일     시도      광명시    음식분류
0       2020-07-01     6  수요일    경기도     의정부시  배달전문업체
1       2020-07-01     7  수요일    경기도     의정부시      찜탕
2       2020-07-01     0  수요일    경기도  고양시 덕양구      야식
3       2020-07-01     1  수요일  인천광역시      부평구      중식
4       2020-07-01     0  수요일  서울특별시     영등포구      치킨
...            ...   ...  ...    ...      ...     ...
6224966 2020-12-31    23  목요일    경기도      포천시   족발/보쌈
6224967 2020-12-31    23  목요일    경기도     의정부시       회
6224968 2020-12-31    23  목요일    경기도      부천시      치킨
6224969 2020-12-31    23  목요일    경기도  안산시 상록구      피자
6224970 2020-12-31    23  목요일   경상북도      김천시      치킨

[6224971 rows x 6 columns]

In [28]:
# 시도에서 서울특별시에 해당하는 데이터만 추출
df_seoul = df.loc[df['시도'].isin(['서울특별시'])]

In [29]:
df_seoul

               년월일  주문시간   요일     시도   광명시 음식분류
4       2020-07-01     0  수요일  서울특별시  영등포구   치킨
9       2020-07-01     1  수요일  서울특별시  영등포구   치킨
10      2020-07-01     1  수요일  서울특별시  영등포구   치킨
14      2020-07-01     0  수요일  서울특별시   금천구   치킨
41      2020-07-01     1  수요일  서울특별시  영등포구   치킨
...            ...   ...  ...    ...   ...  ...
6224912 2020-12-31    23  목요일  서울특별시   구로구   피자
6224913 2020-12-31    23  목요일  서울특별시   구로구   치킨
6224928 2020-12-31    23  목요일  서울특별시   구로구   치킨
6224955 2020-12-31    23  목요일  서울특별시   구로구   치킨
6224956 2020-12-31    23  목요일  서울특별시   구로구   피자

[855952 rows x 6 columns]

In [30]:
df_seoul.reset_index()
df_seoul.reset_index(drop=True, inplace=True)

In [31]:
df_seoul

              년월일  주문시간   요일     시도   광명시 음식분류
0      2020-07-01     0  수요일  서울특별시  영등포구   치킨
1      2020-07-01     1  수요일  서울특별시  영등포구   치킨
2      2020-07-01     1  수요일  서울특별시  영등포구   치킨
3      2020-07-01     0  수요일  서울특별시   금천구   치킨
4      2020-07-01     1  수요일  서울특별시  영등포구   치킨
...           ...   ...  ...    ...   ...  ...
855947 2020-12-31    23  목요일  서울특별시   구로구   피자
855948 2020-12-31    23  목요일  서울특별시   구로구   치킨
855949 2020-12-31    23  목요일  서울특별시   구로구   치킨
855950 2020-12-31    23  목요일  서울특별시   구로구   치킨
855951 2020-12-31    23  목요일  서울특별시   구로구   피자

[855952 rows x 6 columns]

In [32]:
df_seoul = df_seoul[df_seoul.음식분류 != '심부름']
df_seoul = df_seoul[df_seoul.음식분류 != '야식']
df_seoul = df_seoul[df_seoul.음식분류 != '배달전문업체']

In [33]:
df_seoul

              년월일  주문시간   요일     시도   광명시 음식분류
0      2020-07-01     0  수요일  서울특별시  영등포구   치킨
1      2020-07-01     1  수요일  서울특별시  영등포구   치킨
2      2020-07-01     1  수요일  서울특별시  영등포구   치킨
3      2020-07-01     0  수요일  서울특별시   금천구   치킨
4      2020-07-01     1  수요일  서울특별시  영등포구   치킨
...           ...   ...  ...    ...   ...  ...
855947 2020-12-31    23  목요일  서울특별시   구로구   피자
855948 2020-12-31    23  목요일  서울특별시   구로구   치킨
855949 2020-12-31    23  목요일  서울특별시   구로구   치킨
855950 2020-12-31    23  목요일  서울특별시   구로구   치킨
855951 2020-12-31    23  목요일  서울특별시   구로구   피자

[775728 rows x 6 columns]

In [34]:
df_seoul.to_csv("202007~202012지역별요일별배달품목.csv")