In [1]:
# 필요한 모듈 불러오기
import pandas as pd
import numpy as np

In [2]:
# 데이터 파일 불러오기
df = pd.read_csv("./KGU_3rd_ORIGIN_KGUAREADOITEM_20210701000000.csv")

In [3]:
df

        ﻿2021-07-01  00  목요일   충청남도  천안시 동남구  돈까스/일식
0        2021-07-01   0  목요일   충청남도  천안시 동남구   족발/보쌈
1        2021-07-01   0  목요일    경기도     동두천시  돈까스/일식
2        2021-07-01   0  목요일    경기도     동두천시  돈까스/일식
3        2021-07-01   0  목요일   경상북도      영천시  돈까스/일식
4        2021-07-01   0  목요일   경상북도      영천시  돈까스/일식
...             ...  ..  ...    ...      ...     ...
4271690  2021-12-31  23  금요일   경상남도      진주시      분식
4271691  2021-12-31  23  금요일  부산광역시      강서구      치킨
4271692  2021-12-31  23  금요일  부산광역시      강서구      치킨
4271693  2021-12-31  23  금요일  부산광역시      강서구      치킨
4271694  2021-12-31  23  금요일    경기도      군포시  카페/디저트

[4271695 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271695 entries, 0 to 4271694
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   ﻿2021-07-01  object
 1   00           int64
 2   목요일          object
 3   충청남도         object
 4   천안시 동남구      object
 5   돈까스/일식       object
dtypes: int64(1), object(5)
memory usage: 195.5+ MB

In [8]:
df['﻿2021-07-01'] = pd.to_datetime(df['﻿2021-07-01'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271695 entries, 0 to 4271694
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   ﻿2021-07-01  datetime64[ns]
 1   00           int64
 2   목요일          object
 3   충청남도         object
 4   천안시 동남구      object
 5   돈까스/일식       object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 195.5+ MB

In [10]:
# 결측치 확인
df.isnull().sum()

﻿2021-07-01    0
00             0
목요일            0
충청남도           0
천안시 동남구        0
돈까스/일식         0
dtype: int64

In [11]:
# 컬럼명 변경
df.rename(columns={'﻿2021-07-01':'년월일'}, inplace=True)
df.rename(columns={'00':'주문시간'}, inplace=True)
df.rename(columns={'충청남도':'시도'},inplace=True)
df.rename(columns={'목요일':'요일'},inplace=True)
df.rename(columns={'천안시 동남구':'시군구'},inplace=True)
df.rename(columns={'돈까스/일식':'음식분류'},inplace=True)

In [12]:
df

               년월일  주문시간   요일     시도      시군구    음식분류
0       2021-07-01     0  목요일   충청남도  천안시 동남구   족발/보쌈
1       2021-07-01     0  목요일    경기도     동두천시  돈까스/일식
2       2021-07-01     0  목요일    경기도     동두천시  돈까스/일식
3       2021-07-01     0  목요일   경상북도      영천시  돈까스/일식
4       2021-07-01     0  목요일   경상북도      영천시  돈까스/일식
...            ...   ...  ...    ...      ...     ...
4271690 2021-12-31    23  금요일   경상남도      진주시      분식
4271691 2021-12-31    23  금요일  부산광역시      강서구      치킨
4271692 2021-12-31    23  금요일  부산광역시      강서구      치킨
4271693 2021-12-31    23  금요일  부산광역시      강서구      치킨
4271694 2021-12-31    23  금요일    경기도      군포시  카페/디저트

[4271695 rows x 6 columns]

In [13]:
# 시도에서 서울특별시에 해당하는 데이터만 추출
df_seoul = df.loc[df['시도'].isin(['서울특별시'])]

In [14]:
df_seoul.reset_index()
df_seoul.reset_index(drop=True, inplace=True)

In [15]:
df_seoul

              년월일  주문시간   요일     시도  시군구    음식분류
0      2021-07-01     0  목요일  서울특별시  동작구      치킨
1      2021-07-01     0  목요일  서울특별시  금천구  돈까스/일식
2      2021-07-01     0  목요일  서울특별시  금천구  돈까스/일식
3      2021-07-01     0  목요일  서울특별시  금천구  돈까스/일식
4      2021-07-01     0  목요일  서울특별시  금천구      치킨
...           ...   ...  ...    ...  ...     ...
366160 2021-12-31    23  금요일  서울특별시  구로구      야식
366161 2021-12-31    23  금요일  서울특별시  구로구      야식
366162 2021-12-31    23  금요일  서울특별시  강서구      한식
366163 2021-12-31    23  금요일  서울특별시  강서구      야식
366164 2021-12-31    23  금요일  서울특별시  금천구  돈까스/일식

[366165 rows x 6 columns]

In [16]:
df_seoul = df_seoul[df_seoul.음식분류 != '심부름']
df_seoul = df_seoul[df_seoul.음식분류 != '야식']
df_seoul = df_seoul[df_seoul.음식분류 != '배달전문업체']

In [17]:
df_seoul

              년월일  주문시간   요일     시도   시군구    음식분류
0      2021-07-01     0  목요일  서울특별시   동작구      치킨
1      2021-07-01     0  목요일  서울특별시   금천구  돈까스/일식
2      2021-07-01     0  목요일  서울특별시   금천구  돈까스/일식
3      2021-07-01     0  목요일  서울특별시   금천구  돈까스/일식
4      2021-07-01     0  목요일  서울특별시   금천구      치킨
...           ...   ...  ...    ...   ...     ...
366157 2021-12-31    23  금요일  서울특별시  영등포구      찜탕
366158 2021-12-31    23  금요일  서울특별시  영등포구      찜탕
366159 2021-12-31    23  금요일  서울특별시   구로구  돈까스/일식
366162 2021-12-31    23  금요일  서울특별시   강서구      한식
366164 2021-12-31    23  금요일  서울특별시   금천구  돈까스/일식

[354244 rows x 6 columns]

In [18]:
df_seoul.to_csv("202107~202112지역별요일별배달품목.csv")